media:
  input: static/images
  output: /images

content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
            input: static/images
            output: /images
            extensions: [ jpg, jpeg, png ]
      - name: date
        label: Date
        type: date
      - name: tags
        label: Tag
        type: select
        list: true
        options:
          values:
            - announcements
            - notes
            - events
        default: ["announcements"]
      - name: cover
        label: Cover
        type: object
        fields:
          - name: image
            label: Image
            type: image
            required: false
      - name: weight
        label: Priority
        type: number
        required: false
      - name: draft
        label: Draft
        type: boolean
        default: false

  - name: contact
    label: Contact Page
    path: content/contact/index.md
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
            input: static/images
            output: /images
            extensions: [ jpg, jpeg, png ]      

  - name: manuals
    label: Manuals Page
    path: content/manuals/index.md
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
            input: static/images
            output: /images
            extensions: [ jpg, jpeg, png ]

  - name: faq
    label: FAQ Page
    path: content/faq/index.md
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
            input: static/images
            output: /images
            extensions: [ jpg, jpeg, png ]
